### ISSUE TITLE
Feature request: Video component

### ISSUE THREAD

**Issue by henrykuijpers** [Adobe-Marketing-Cloud/aem-core-wcm-components#148] opened 2018-04-03 14:56 UTC
Just like we have the Image-component, it would be nice to have a Video-component. This component should work the same way the Image-component does: You either specify a video asset, or you upload a video directly.

**Comment by richardhand** [comment] 2018-05-18 14:13
Thanks @henrykuijpers for the suggestion, a new video component is on our roadmap (https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/wiki).

**Comment by kwin** [comment] 2018-06-28 19:39
Isn’t this a duplicate of #218?

**Comment by jckautzmann** [comment] 2018-06-29 06:44
@kwin You're correct. I'm closing this issue. Let's continue the discussion on #218.

**Closed by jckautzmann** 2018-06-29 06:44 UTC

**Comment by gabrielwalt** [comment] 2018-07-04 16:50
Note that for now, the RTC on #218 doesn't allow direct upload on the component, and only referencing a video from DAM. The reason for this is that there probably needs to be a workflow triggered when uploading a video to generate the different encodings that might be needed.
