### ISSUE TITLE
Image component doesn't show previously selected image 

### ISSUE THREAD

**Issue by josephh** [Adobe-Marketing-Cloud/aem-core-wcm-components#173] opened 2018-04-30 15:49 UTC
Hi, apologies if this is a usage issue only.

Running AEM 6.3 with SP1 and SP2 installed. 
Trying out versions 1 and 2 of the /apps/core/wcm/components/image component by maven installing the tutorial https://github.com/Adobe-Marketing-Cloud/aem-guides-wknd/tree/p2.

1. Use the text component to drop an image on the "Drop an asset here..." cq/gui/components/authoring/dialog/fileupload field.  Thumbnail image shows in dialogue.
1. Confirm the dialogue to close it - selected image shows on authored page.
1. Re-open the dialogue, thumbnail image does not show ❗️.  
Is this by design (or something not working)?
  
![image](https://user-images.githubusercontent.com/1249267/39436524-1a669572-4c96-11e8-88ed-954fc4db7721.png)

![image](https://user-images.githubusercontent.com/1249267/39436564-39f48e8a-4c96-11e8-9348-66380e067dfe.png)

![image](https://user-images.githubusercontent.com/1249267/39436626-6351b1e0-4c96-11e8-8718-47f2dbb5eac4.png)

**Comment by kwin** [comment] 2018-04-30 17:47
I think this is a duplicate of #101.

**Comment by bpauli** [comment] 2018-05-02 15:33
@josephh, as already mentioned by @kwin, this is a duplicate of #101 and will be fixed with the Cumulative Fix Pack 6.3.2.2. For a workaround please see the comments on #101. Thanks!

**Closed by bpauli** 2018-05-02 15:33 UTC
Labels: question
