### ISSUE TITLE
Nullpointer in NavigationImpl when Redirect Target is not found

### ISSUE THREAD

**Issue by bastronaut** [Adobe-Marketing-Cloud/aem-core-wcm-components#189] opened 2018-05-23 09:28 UTC
## Bug Report

**Current Behavior**
We are facing a NPE in the [NavigationImpl](https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/blob/master/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/NavigationImpl.java) class breaking the View As published mode when we make 'creative' use of the _cq:redirectTarget_  property of a page. 

We are trying to support the following behaviour: 
- A 'tab' component on a a page (call it _page-target.html_) has a bunch of tabs and panels. 
- On page load, it looks at the current URL, checks for the presence of a hash (#) followed by an id of the panel. For ex: _/content/page-target.html#tab-number-one_
- It opens the page with the panel given in the url.
- Some of our pages redirect to this _page-target.html_ by putting in the cq:redirectTarget field the value: _/content/page-target.html#tab-number-one_

Now, the following snippet [(line 197)](https://github.com/Adobe-Marketing-Cloud/aem-core-wcm-components/blob/master/bundles/core/src/main/java/com/adobe/cq/wcm/core/components/internal/models/v1/NavigationImpl.java#L197) causes a NPE when we use the redirectTarget path with a hash, as there is no NP check on redirectPage:

```
if(StringUtils.isNotBlank(redirectTarget)) {
                PageManager pageManager = resourceResolver.adaptTo(PageManager.class);
                if (pageManager != null) {
                    Page redirectPage = pageManager.getPage(redirectTarget);
                    if (redirectPage.equals(currentPage)) {
                        currentPageIsRedirectTarget = true;
                    }
                }
            }
```

Now, if you say we are abusing the redirectTarget field and we should find a different way to do this: I probably will, open to suggestions ;). However, a NP check there may not be a bad idea. There may be other cases where getPage() returns null, perhaps when the page has been removed? 

**Expected behavior/code**
No nullpointer exception

**Environment**
-  AEM 6.3 SP 2, Core components 2.0.6

**Possible Solution**
Add a null check to redirectPage :)

**Comment by bastronaut** [comment] 2018-05-23 09:36
Confirmed, the following will cause a NPE:

1. Add a Redirect Target property to a page. 
2. Delete the page that is given in 1
3. NPE

Best,

Bas

**Comment by gabrielwalt** [comment] 2018-05-23 09:40
Nice find, thanks @bastronaut, we'll fix that in the next release asap!

**Comment by kwin** [comment] 2018-05-23 10:35
Just reverting the condition should be enough to prevent the NPE
From `if (redirectPage.equals(currentPage)) {` to `if (currentPage.equals(redirectPage)) {`. But IMHO so whole logic is not enough, as the redirectTarget may also contain aliases and URLs with extensions and fragments. So most probably the given URL needs to be parsed first, and then the path part of the url needs to be resolved via the resource resolver to check if the given resource is equal to the current page.

**Comment by bastronaut** [comment] 2018-05-23 11:38
Hi @kwin,

Agree that it would be better to improve resolving the redirectPage here. I'm not familiar with fragments and its impact on this scenario. Can you elaborate on this part?

**Comment by kwin** [comment] 2018-05-23 16:05
This might actually be a duplicate of #174

**Closed** 2018-06-04 13:00 UTC
Labels: bug, duplicate
